/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fengneng_controller_TestNative */

#ifndef _Included_com_fengneng_controller_TestNative
#define _Included_com_fengneng_controller_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fengneng_controller_TestNative
 * Method:    testNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fengneng_controller_TestNative_testNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
